### ISSUE TITLE
Codecs

### ISSUE THREAD

**Issue by JimBobSquarePants** [SixLabors/ImageSharp#10]
_From @JimBobSquarePants on August 4, 2016 6:15_

This issue serves to collect various issues with the image codecs. Additional issues will be added upon identification.

Png
- [x] Decoder doesn't decode progressive files #379 
- [x]  Encoder does not encode progressive files

Jpeg
- [x] Decoder does not decode CMYK files #444 
- [ ] Encoder does not encode CMYK files
- [ ] Encoder does not encode progressive files

Tiff
- [ ] No Tiff support #464 

_Copied from original issue: JimBobSquarePants/ImageProcessor#446_
