### ISSUE TITLE
System.Memory API integration

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#565]
### Goals
Thanks to #558, we are now able to expose `System.Memory` API-s allowing efficient interop operations. However, we need to distinguish between different use-cases, because they raise design problems of different difficulty levels. In some use-cases we have to decide whether we should expose `Span<T>`, `Memory<T>` or both.

### "Official" guideline on System.Memory
Managed to find a WIP (?) documentation on `Memory<T>`. (It was mentioned in [coreclr/#17340](https://github.com/dotnet/coreclr/pull/17340))
- [Memory<T> API documentation and samples](https://gist.github.com/GrabYourPitchforks/8efb15abbd90bc5b128f64981766e834)
- [Memory<T> usage guidelines](https://gist.github.com/GrabYourPitchforks/4c3e1935fd4d9fa2831dbfcab35dffc6)

### Tasks
- [x] Basic `ReadOnlySpan<T>` overloads of [LoadPixelData](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Image.LoadPixelData.cs) (done in #567)
- [x] `ReadOnlySpan<T>` overloads for [`Image.Load()` and `Image.DetectFormat()`](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Image.FromBytes.cs#L44). See @jherby2k's [proposal](https://github.com/SixLabors/ImageSharp/issues/565#issuecomment-388057174).
  - We can pin the span and use [`UnmanagedMemoryStream`](https://msdn.microsoft.com/en-us/library/system.io.unmanagedmemorystream%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) for this.
- [x] Integrate `System.Memory.IMemoryOwner<T>` and/or `System.Memory.MemoryManager<T>` with [`SL.ImageSharp.Memory.IBuffer<T>`](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Memory/IBuffer%7BT%7D.cs)
  	- Prerequisite for using `Memory<T>`, thus for the following 2 points
  	- ~Notice the name collision with `SL.ImageSharp.Memory.MemoryManager<T>` :P~ **UPDATE:** SixLabors stuff is now called `MemoryAllocator`
- [x] `Image.Wrap(existingMemoryArea)` or similar.
  - Very useful for interop scenarios, see #435 or #88
  - ~[Already added as internal](https://github.com/SixLabors/ImageSharp/blob/master/src/ImageSharp/Image.WrapMemory.cs#L29), need to validate the API through a real-life use-case.~ DONE
- [x] Expose `image.GetPixelSpan()` and `image.GetPixelRowSpan()`
  - Note: this API can lead to unintended heap capture issues many users fail to understand
- [x] Expose `image.GetPixelSpan()` and `image.GetPixelRowSpan()`
  - Only if possible/allowed by the guideline. See [these issues](https://github.com/SixLabors/ImageSharp/pull/607#discussion_r194516147) for more information about the blockers!
  - We decided to not expose `Memory<T>` for now
- [x] Move the core memory management classes out of this repo. They should live in [SixLabors.Core](https://github.com/SixLabors/Core) so we can integrate them across the whole SixLabors stack. (#619)

**Comment by jherby2k** [comment]
I'd really like to see these, as a consumer of this library. I recognize that in most cases you're going to have to just copy the span to an array (ArrayPooled?) to use with Memorystream, but eventually (.NET Standard 3, apparently) streams will be able to read from Spans directly. So by adding the APIs now, the allocation-free path is an implementation detail for later.

`public static IImageFormat DetectFormat(ReadOnlySpan<byte> data);

public static IImageFormat DetectFormat(Configuration config, ReadOnlySpan<byte> data);

public static Image<Rgba32> Load(ReadOnlySpan<byte> data);

public static Image<Rgba32> Load(ReadOnlySpan<byte> data, out IImageFormat format);

public static Image<Rgba32> Load(Configuration config, ReadOnlySpan<byte> data);

public static Image<Rgba32> Load(Configuration config, ReadOnlySpan<byte> data, out IImageFormat format);

public static Image<Rgba32> Load(ReadOnlySpan<byte> data, IImageDecoder decoder);

public static Image<Rgba32> Load(Configuration config, ReadOnlySpan<byte> data, IImageDecoder decoder);

public static Image<TPixel> Load<TPixel>(ReadOnlySpan<byte> data);

public static Image<TPixel> Load<TPixel>(ReadOnlySpan<byte> data, out IImageFormat format);

public static Image<TPixel> Load<TPixel>(Configuration config, ReadOnlySpan<byte> data);

public static Image<TPixel> Load<TPixel>(Configuration config, ReadOnlySpan<byte> data, out IImageFormat format);

public static Image<TPixel> Load<TPixel>(ReadOnlySpan<byte> data, IImageDecoder decoder);

public static Image<TPixel> Load<TPixel>(Configuration config, ReadOnlySpan<byte> data, IImageDecoder decoder);`

**Comment by antonfirsov** [comment]
@jherby2k I like your API proposal pretty much, we should implement it.
But it's important to make sure we have good docs on these methods, because currently it's very easy to confuse `Load()` with `LoadPixelData()`.

Our current docs on `Image.Load(byte[] data)` aren't really helpful:
```
Create a new instance of the <see cref="Image{Rgba32}"/> class from the given byte array.
```

**Comment by hypeartist** [comment]
@antonfirsov @JimBobSquarePants Additional info on Span<T> and Memory<T> stuff:
[C# - All About Span: Exploring a New .NET Mainstay](https://msdn.microsoft.com/en-us/magazine/mt814808.aspx)

**Comment by jherby2k** [comment]
Well I alluded to that in my request... at the time it was announced that the spanified Steams would be coming to netstandard 3.0 / .net 4.8 but now it sounds like that isn’t going to be the case. My suggestion is to either start multitargetting

**Comment by antonfirsov** [comment]
@jherby2k unfortunately, "spanified stream" isn't a thing that helps here, but I figured it out!
We can pin the span and use [`UnmanagedMemoryStream`](https://msdn.microsoft.com/en-us/library/system.io.unmanagedmemorystream%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396).

Gonna PR it soon.

**Comment by jherby2k** [comment]
Did not know about that one! That’s great.

Just to clarify though, by “spanified stream” I’m referring to .net core 2.1’s Stream.Write(Span<byte> buffer) overload. Which is exactly what you’re looking for, but obviously isn’t available for .net standard.

**Comment by antonfirsov** [comment]
@jherby2k ahh, you mean creating a `MemoryStream` and writing the span into it? I wanted to avoid this, it's a huge allocation :)

**Comment by antonfirsov** [comment]
We may need to introduce further API changes to allow handling very large unmanaged buffers and memory mapped files, but the topic is not yet clear for me. I'm leaving a few links here, so we can find them later:
- [An article on the new API-s](https://www.codemag.com/Article/1807051/Introducing-.NET-Core-2.1-Flagship-Types-Span-T-and-Memory-T)
- Memory-mapped files and `Memory<T>`: dotnet/corefx#26603

**Comment by antonfirsov** [comment]
Best System.Memory article so far:
https://www.codemag.com/Article/1807051/Introducing-.NET-Core-2.1-Flagship-Types-Span-T-and-Memory-T

**Comment by antonfirsov** [comment]
All tasks are done, so I'm closing this epic.
