### ISSUE TITLE
Epic: introduce pixel-agnostic API across the whole library

### ISSUE THREAD

**Issue by antonfirsov** [SixLabors/ImageSharp#907]
I'm opening this to track the API changes I'm planning to introduce in multiple PR-s:
- [x] Adding the non-generic `Image` base class, refactor and publish processors without color parameters. (#904)
- [x] Introduce pixel [independant color type](https://gist.github.com/antonfirsov/ba3b3fc05e7aba19458d6d61c8b38e2c), refactor and publish processors having color values as parameters.
- [x] Make **ImageSharp.Drawing** API non-generic.
- [x] Do a sanity check on the resulting API set. Drop (or consider dropping) generic classes made obsolete by the new API (`ColorBuilder<T>`, `NamedColors<T>` and `ImageProcessingContext<T>`)
- [x] Define (or at least considerdefining) a non-generic variant of `ImageFrameCollection`
- [x] Update SixLabors/Samples (also taking [other aspects](https://github.com/SixLabors/ImageSharp/issues/931#issuecomment-501575653) into account)
- [x] Anaylize impact on AOT, extend `AotCompilerTools`. **EDIT:** Won't do it for RC1. Moved to separate issue: #946.

After finishing the changes, I'm planning to publish a blog post to explain the new API and help existing users with a migration guide.

**Comment by antonfirsov** [comment]
All points are finished here, including the update of the [Samples](https://github.com/SixLabors/Samples), closing!
